const EXTERNAL_API = 'http://192.168.0.101:8080';

const ROUTER = {
    GET_PLACE_DATA: '/api/place/',
    UPDATE_PLACE_DATA: '/api/place/update/',
    GET_PLACE_PRODUCTS: '/api/products/' /* place_id / category_id["Todo"] */,
    CREATE_PRODUCT: '/api/product/create',
    UPDATE_PRODUCT: '/api/product/update',
    DELETE_PRODUCT: '/api/product/delete'
};

export default {
    GET_PLACE_DATA_API: EXTERNAL_API + ROUTER.GET_PLACE_DATA,
    UPDATE_PLACE_DATA_API: EXTERNAL_API + ROUTER.UPDATE_PLACE_DATA,
    GET_PLACE_PRODUCTS_API: EXTERNAL_API + ROUTER.GET_PLACE_PRODUCTS,
    CREATE_PRODUCT_API: EXTERNAL_API + ROUTER.CREATE_PRODUCT,
    UPDATE_PRODUCT_API: EXTERNAL_API + ROUTER.UPDATE_PRODUCT,
    DELETE_PRODUCT_API: EXTERNAL_API + ROUTER.DELETE_PRODUCT
}
